fix: 修复个人热点无法开启问题
linuxdeepin/dde-network-core pull request #102
Opened 2022-11-29 14:13 UTC by caixr23

开启热点未设置ssid

Log: 修复个人热点无法开启问题
Bug: https://pms.uniontech.com/bug-view-174545.html
Influence: 控制中心-开启个人热点

2022-11-29 14:16 UTC, ut003640 approved these changes

2022-11-29 14:20 UTC, caixr23 commented
I have read the CLA Document and I hereby sign the CLA.

2022-11-29 14:28 UTC, BLumia requested changes
公司员工无需签署个人 CLA，请注意提交代码时需要使用公司的邮箱。请检查 `git config user.email` 配置。

2022-11-29 15:15 UTC, caixr23 commented
\Merge

2022-11-29 15:16 UTC, caixr23 commented
\merge

2022-11-30 01:20 UTC, KT-lcz approved these changes

2022-11-30 01:25 UTC, merged