feat: remove the ip only check for add vpn
linuxdeepin/dde-network-core pull request #6
Opened 2022-07-13 07:47 UTC by kt286

remove the ip only check for add vpn

Log: remove the ip only check for add vpn

2022-07-13 10:36 UTC, BLumia commented
May resolve https://github.com/linuxdeepin/developer-center/issues/3304 ?

2022-07-15 05:51 UTC, zccrs requested changes

2022-07-15 05:51 UTC, zccrs commented on dcc-network-plugin/sections/vpn/vpnopenconnectsection.cpp
> -    if (m_gateway->text().isEmpty() || !isIpv4Address(m_gateway->text())) {
把 isIpv4Address 换成 QHostAddress::isNull 试试？

2022-07-18 07:57 UTC, zccrs commented
/+1

2022-07-19 09:39 UTC, ssk-wh approved these changes

2022-07-19 09:40 UTC, ssk-wh commented
/merge

2022-07-19 09:55 UTC, BLumia commented
@ssk-wh 这个 build-deb 的问题主线解决了吗？解决了的话 rebase 一下应该就行了

2022-07-19 10:07 UTC, ssk-wh commented
没，公司里还在处理

2022-07-19 11:20 UTC, ssk-wh commented
手动合吧

2022-07-19 11:26 UTC, merged